name: Deploy Project

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          cd my-portfolio
          npm ci
          npm run build

      - name: Deploy via oprypin
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: my-portfolio/dist
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
