name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd my-portfolio 
          npm install
          ls

      - name: Build project
        run: |
          ls
          cd my-portfolio 
          ls
          npm run build

      - name: Deploy to GitHub Pages
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: ./my-portfolio/dist
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
